{
    'name': 'Tire and Loading Info',
    'version': '15.0.1.0.1',
    'category': 'Inventory',
    'summary': "Print format for tire and loading info'",
    'author': 'Sursoom',
    'maintainer': 'Sursoom',
    'company': 'Sursoom',
    'website': 'https://www.sursoom.mx',
    'description': """Imprime reporte del formato'""",
    'depends': ['stock',
                'stock_account',
                'purchase',
                'base'
                ],
    'images': ['static/description/banner.png'],
    'license': 'AGPL-3',
    'application': False,
    'installable': True,
    'auto_install': False,
}
