# -*- coding: utf-8 -*-
# Part of Odoo Module Developed by 73lines
# See LICENSE file for full copyright and licensing details.


{
    'name': 'Snippet Multi Boxed By 73Lines',
    'description': 'Snippet Multi Boxed By 73Lines',
    'category': 'Website',
    'version': '15.0.1.0.0',
    'author': '73Lines',
    'website': 'https://www.73lines.com/',
    'depends': ['website',
                'website_icon_fonts_ul_73lines'],
    'data': [
        'views/assets.xml',
        'views/s_carousel_and_images.xml',
        'views/s_three_images.xml',
        'views/s_three_same_size_images.xml',
        'views/s_two_images.xml',
        'views/s_one_carousel_one_image.xml',
        'views/s_one_carousel_three_images.xml',
        'views/s_four_images.xml',
        'views/s_promo_image.xml',
        'views/s_grid_images.xml',
        'views/s_half_carousel_half_image_left.xml',
        'views/s_half_carousel_half_image_right.xml',
        'views/s_half_carousel_half_carousel.xml',
        'views/s_three_boxes_with_icon.xml',
        'views/s_3x6x3.xml',
        'views/s_3x5x4.xml',
        'views/s_4x4x4.xml',
        'views/s_logo_image.xml',
        'views/s_ecommerce_terms.xml',
        'views/s_counter_text.xml',
        'views/s_presentation_page.xml',
        'views/s_progress_bar.xml',
        'views/s_skill_chart.xml',
        'views/s_client_intro.xml',
        'views/s_store_ecommerce_service.xml',
        'views/s_ecommerce_service.xml',
        'views/s_bar_chart.xml',
        'views/s_media_block.xml',
    ],
    'assets': {
        'web.assets_frontend': [
                '/website_snippet_boxed_ul_73lines/static/src/scss/s_carousel_and_images.scss',
                '/website_snippet_boxed_ul_73lines/static/src/scss/s_promo_images.scss',
                '/website_snippet_boxed_ul_73lines/static/src/scss/s_three_boxes_with_icon.scss',
                '/website_snippet_boxed_ul_73lines/static/src/scss/s_ecommerce_terms.scss',
                '/website_snippet_boxed_ul_73lines/static/src/scss/s_progress_bar.scss',
                '/website_snippet_boxed_ul_73lines/static/src/scss/odometer-theme-minimal.scss',
                '/website_snippet_boxed_ul_73lines/static/src/scss/jquery.fullPage.scss',
                '/website_snippet_boxed_ul_73lines/static/src/scss/jquery.easy-pie-chart.scss',
                '/website_snippet_boxed_ul_73lines/static/src/scss/odometer.scss',
                '/website_snippet_boxed_ul_73lines/static/src/scss/skill_chart.scss',
                '/website_snippet_boxed_ul_73lines/static/src/scss/s_client_intro.scss',
                '/website_snippet_boxed_ul_73lines/static/src/scss/s_ecommerce_service.scss',
                '/website_snippet_boxed_ul_73lines/static/src/scss/s_store_ecommerce_service.scss',
                '/website_snippet_boxed_ul_73lines/static/src/scss/s_bar_chart.scss',

                '/website_snippet_boxed_ul_73lines/static/src/js/jquery.appear.js',
                '/website_snippet_boxed_ul_73lines/static/src/js/chart.js',
                '/website_snippet_boxed_ul_73lines/static/src/js/jquery.easy-pie-chart.js',
                '/website_snippet_boxed_ul_73lines/static/src/js/odometer.js',
                # '/website_snippet_boxed_ul_73lines/static/src/js/fullPage.js',
                '/website_snippet_boxed_ul_73lines/static/src/js/main.js',
                '/website_snippet_boxed_ul_73lines/static/src/js/s_ecommerce_service.js',
                '/website_snippet_boxed_ul_73lines/static/src/js/jquery.mb.YTPlayer.js',
                '/website_snippet_boxed_ul_73lines/static/src/js/s_media_block_frontend.js',
                '/website_snippet_boxed_ul_73lines/static/src/js/snippet.ext.frontend.js',
        ],

        'website.assets_editor': [
            '/website_snippet_boxed_ul_73lines/static/src/js/s_state_box.js',
            '/website_snippet_boxed_ul_73lines/static/src/js/s_client_intro_editor.js',
            '/website_snippet_boxed_ul_73lines/static/src/js/snippet.ext.editor.js',
            '/website_snippet_boxed_ul_73lines/static/src/js/bar_chart.js',
            '/website_snippet_boxed_ul_73lines/static/src/js/rte_options.js',
            '/website_snippet_boxed_ul_73lines/static/src/js/progress_bar.js',
            '/website_snippet_boxed_ul_73lines/static/src/js/s_media_block_editor.js',
        ],

    },
    'images': [
        'static/description/website_snippet_boxed_ul_73lines.jpg',
    ],
    'price': 50,
    'license': 'OPL-1',
    'currency': 'EUR',
}
